# Generated by Django 3.1.5 on 2021-01-23 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('tipo_anime', models.CharField(max_length=10, verbose_name='Tipo Anime')),
                ('rating', models.FloatField(verbose_name='Rating')),
                ('num_votos', models.IntegerField(verbose_name='Número de Votos')),
                ('estado', models.CharField(max_length=10, verbose_name='Estado')),
                ('seguidores', models.IntegerField(verbose_name='Seguidores')),
                ('generos', models.CharField(max_length=100, verbose_name='Género')),
                ('indice', models.IntegerField(verbose_name='Índice')),
            ],
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='Username')),
                ('puntuacion', models.IntegerField(verbose_name='Puntuación')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.anime')),
            ],
        ),
    ]
